inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    
AllCops:
  Exclude:
    - tmp/**/**
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/**

Rails/DynamicFindBy:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
