inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - tmp/**/**
    - db/schema.rb
    - db/migrate/201*.rb

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - spec/**/**

Rails/DynamicFindBy:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
