<% fake_base_url = "http://fake-notify.com" %>

development:
  base_url: <%= ENV.fetch('GOVUK_NOTIFY_BASE_URL', fake_base_url) %>

test:
  base_url: <%= ENV.fetch('GOVUK_NOTIFY_BASE_URL', fake_base_url) %>

production:
  base_url: <%= ENV.fetch('GOVUK_NOTIFY_BASE_URL', nil) %>
