<% fake_api_key = "fake_api_key-00000000-0000-0000-0000-000000000000-00000000-0000-0000-0000-000000000000" %>
<% fake_base_url = "http://fake-notify.com" %>

development:
  api_key: <%= ENV.fetch('GOVUK_NOTIFY_API_KEY', fake_api_key) %>
  base_url: <%= ENV.fetch('GOVUK_NOTIFY_BASE_URL', fake_base_url) %>

test:
  api_key: <%= ENV.fetch('GOVUK_NOTIFY_API_KEY', fake_api_key) %>
  base_url: <%= ENV.fetch('GOVUK_NOTIFY_BASE_URL', fake_base_url) %>

production:
  api_key: <%= ENV.fetch('GOVUK_NOTIFY_API_KEY', nil) %>
  base_url: <%= ENV.fetch('GOVUK_NOTIFY_BASE_URL', nil) %>
