---
:verbose: false
:concurrency: 32
:logfile: ./log/sidekiq.json.log
:timeout: 4
:queues:
  # See here to understand priorities: https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues
  # Use powers of 2: higher priority groups are checked twice as often.
  - [delivery_transactional, 8] # To send one-off emails, such as subscription confirmation.
  - [delivery_immediate_high, 8] # To send high priority emails to users with immediate subscriptions e.g. travel advice.
  - [process_and_generate_emails, 4] # To generate emails to users with immediate subscriptions for content changes and messages.
  - [email_generation_digest, 4] # To generate emails to users with daily or weekly subscriptions for content changes and messages.
  - [delivery_immediate, 2] # To send emails to users with immediate subscriptions.
  - [delivery_digest, 2] # To send digest emails to users with either daily or weekly subscriptions.
  - [default, 1] # Miscellaneous operations e.g. initiating digest runs, monitoring, DB cleanup and recovering lost Sidekiq jobs.
:schedule:
  daily_digest_initiator:
    cron: '30 8 * * * Europe/London' # every day at 8:30am
    class: DailyDigestInitiatorWorker
  weekly_digest_initiator:
    cron: '30 8 * * 6 Europe/London' # every Saturday at 8:30am
    class: WeeklyDigestInitiatorWorker
  nullify_deactivated_subscribers:
    every: '1h'
    class: NullifyDeactivatedSubscribersWorker
  email_archiver:
    every: '1h'
    class: EmailArchiveWorker
  email_deleter:
    every: '1h'
    class: EmailDeletionWorker
  digest_run_completion_marker:
    every: '1m'
    class: DigestRunCompletionMarkerWorker
  metrics_collection:
    every: '1m'
    class: MetricsCollectionWorker
  recover_lost_jobs:
    every: '30m'
    class: RecoverLostJobsWorker
