---
:verbose: false
:concurrency: 22
:logfile: ./log/sidekiq_send_email.json.log
:timeout: 4
:max_retries: 9
:queues:
  # See here to understand priorities: https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues
  # Use powers of 2: higher priority groups are checked twice as often.
  - [send_email_transactional, 4] # To send one-off emails, such as subscription confirmation.
  - [send_email_immediate_high, 4] # To send high priority emails to users with immediate subscriptions e.g. travel advice.
  - [send_email_immediate, 1] # To send emails to users with immediate subscriptions.
  - [send_email_digest, 1] # To send digest emails to users with either daily or weekly subscriptions.
